### ISSUE TITLE
Undefined index: virtual_device in munkireport-4.0.1/vendor/munkireport/displays_info/displays_info_model.php

### ISSUE THREAD

**Issue by arekdist** [munkireport/displays_info#2]
After upgrade to munkireport 4.0.1 managedsoftwareupdate -v reports:

`<br />
<b>Notice</b>:  Undefined index: virtual_device in <b>/usr/share/nginx/html/munkireport-4.0.1/vendor/munkireport/displays_info/displays_info_model.php</b> on line <b>195</b><br />`

I occurs randomly on each client, but usually on first run.
Server linux, debian 9.6, Nginx 1.10.3, mariadb-server-10.2

**Comment by tuxudo** [comment]
Thank you for the bug report! :D Added an additional check for the key and pushed a new release
